version: 0.0
os: linux
files:
  - source: /vendor/
    destination: /home/ec2-user/serverpod/upload/vendor/
  - source: /family_photo_server/
    destination: /home/ec2-user/serverpod/upload/family_photo_server/
hooks:
  BeforeInstall:
    - location: family_photo_server/aws/scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: family_photo_server/aws/scripts/start_server
      timeout: 300
      runas: root
