version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: family_photo
      POSTGRES_PASSWORD: "NdetJFtNbbt9GcI1l2ModSiZ_wZstb6I"
    volumes:
      - family_photo_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "DZUhTuJxA3Rtwz3CmWbzlK1W0DUip0A8"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  family_photo_data:
